@MercurialBackendDotnet_HostAddress = http://localhost:5066
@Token = 

@Refresh = 

### Create topic
POST {{MercurialBackendDotnet_HostAddress}}/assignment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "title":"Taller de expresiones regulares",
  "subjectId":2,
  "topicId":5,
  "noteContent":"Crear 5 expresiones regulares, cada uno con su lenguaje y autómata",
  "dueDate": "2025-04-15T18:30:00Z"
}

### Updateassignment
PUT {{MercurialBackendDotnet_HostAddress}}/assignment
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "assignmentId":"e6002d5c-94d0-4b9d-8694-905e3f0b5f44",
  "title":"Taller de expresiones regulares (TLF)",
  "subjectId":2,
  "topicId":7,
  "noteContent":"Crear 10 expresiones regulares, cada uno con su lenguaje y autómata y gráfica",
  "dueDate": "2025-04-17T18:30:00Z"
}

### Delete assignment
DELETE  {{MercurialBackendDotnet_HostAddress}}/assignment/5b7eedf7-9a2d-479b-ad69-5d6f82c2a9e5
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}


### Get User assignments
GET   {{MercurialBackendDotnet_HostAddress}}/assignment/todoAssignments?offset=0&limit=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Get User assignments (done)
GET   {{MercurialBackendDotnet_HostAddress}}/assignment/doneAssignments?offset=0&limit=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}


### Mark assignment as done
PATCH {{MercurialBackendDotnet_HostAddress}}/assignment/markAsDone/e6002d5c-94d0-4b9d-8694-905e3f0b5f44
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}


### Mark assignment as done
PATCH {{MercurialBackendDotnet_HostAddress}}/assignment/markAsDone/e6002d5c-94d0-4b9d-8694-905e3f0b5f44
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}
