@MercurialBackendDotnet_HostAddress = http://localhost:5066
@Token = 

@Refresh = 

### Create topic
POST {{MercurialBackendDotnet_HostAddress}}/checklist
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "assignmentId":"e6002d5c-94d0-4b9d-8694-905e3f0b5f44"
}

### Add node
POST {{MercurialBackendDotnet_HostAddress}}/checklist/addNode
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "listId":2,
  "content":"Desarrollar modulos del frontend"

}

### Delete checklist
DELETE  {{MercurialBackendDotnet_HostAddress}}/checklist/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}


### Get assignment checklist
GET   {{MercurialBackendDotnet_HostAddress}}/checklist/e6002d5c-94d0-4b9d-8694-905e3f0b5f44
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Get User checklists
DELETE  {{MercurialBackendDotnet_HostAddress}}/checklist/removeNode/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Get User checklists
PATCH {{MercurialBackendDotnet_HostAddress}}/checklist/markAsDoneNode/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Get User checklists
PATCH {{MercurialBackendDotnet_HostAddress}}/checklist/unmarkAsDoneNode/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}
