@MercurialBackendDotnet_HostAddress = http://localhost:5066
@Token = 

@Refresh = 

### Create topic
POST {{MercurialBackendDotnet_HostAddress}}/topic
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "title":"formulación",
  "Color":"#456456"
}

### UpdateTopic
PUT {{MercurialBackendDotnet_HostAddress}}/topic
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "topicId":12,
  "title":"Teoría de lenguajes formales",
  "color":"#890123"
}

### Delete Topic
DELETE  {{MercurialBackendDotnet_HostAddress}}/topic/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}


### Get User topics
GET   {{MercurialBackendDotnet_HostAddress}}/topic?offset=0&limit=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}
