@MercurialBackendDotnet_HostAddress = http://localhost:5066
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjBlZjdhMmNkLWUwZmUtNDQ3ZS04YzQ0LWJlYjZlOTM2ZmQ1MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InZhcmdhc2xvYWl6YWNyaXN0aWFuQGdtYWlsLmNvbSIsImV4cCI6MTc0NDgyMjUyOSwiaXNzIjoiTWVyY3VyaWFsIiwiYXVkIjoiTWVyY3VyaWFsRnJvbnQifQ.Unn3JKvJ5bBn0vF-iLMb4xdcE90-KZ3vrmihJaWdzkc

@Refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjBlZjdhMmNkLWUwZmUtNDQ3ZS04YzQ0LWJlYjZlOTM2ZmQ1MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InZhcmdhc2xvYWl6YWNyaXN0aWFuQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2F1dGhlbnRpY2F0aW9uIjoiMWJkOTk5MjYtNDEwMi00OGQyLWJjMDUtMGU2ZWNjNTVjNmE0IiwiZXhwIjoxNzQ1MjgxOTM1LCJpc3MiOiJNZXJjdXJpYWwiLCJhdWQiOiJNZXJjdXJpYWxGcm9udCJ9.84xTtS9RA3NYT0gT-OVsYCGowDHnOJf4WYDFpFQ8Wag

### Create topic
POST {{MercurialBackendDotnet_HostAddress}}/checklist
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "assignmentId":"e6002d5c-94d0-4b9d-8694-905e3f0b5f44"
}

### Add node
POST {{MercurialBackendDotnet_HostAddress}}/checklist/addNode
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "listId":2,
  "content":"Desarrollar modulos del frontend"

}

### Delete checklist
DELETE  {{MercurialBackendDotnet_HostAddress}}/checklist/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}


### Get assignment checklist
GET   {{MercurialBackendDotnet_HostAddress}}/checklist/e6002d5c-94d0-4b9d-8694-905e3f0b5f44
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Get User checklists
DELETE  {{MercurialBackendDotnet_HostAddress}}/checklist/removeNode/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Get User checklists
PATCH {{MercurialBackendDotnet_HostAddress}}/checklist/markAsDoneNode/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

### Get User checklists
PATCH {{MercurialBackendDotnet_HostAddress}}/checklist/unmarkAsDoneNode/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}
