@MercurialBackendDotnet_HostAddress = http://localhost:5066
@Token =

@Refresh = 

### Create topic
POST {{MercurialBackendDotnet_HostAddress}}/subject
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "title":"Gestión de proyectos"
}

### Updatesubject
PUT {{MercurialBackendDotnet_HostAddress}}/subject
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "subjectId":1,
  "title":"Cloud Computing"
}

### Delete subject
DELETE  {{MercurialBackendDotnet_HostAddress}}/subject/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}


### Get User subjects
GET   {{MercurialBackendDotnet_HostAddress}}/subject?offset=0&limit=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}
