@MercurialBackendDotnet_HostAddress = http://localhost:5066
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjBlZjdhMmNkLWUwZmUtNDQ3ZS04YzQ0LWJlYjZlOTM2ZmQ1MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InZhcmdhc2xvYWl6YWNyaXN0aWFuQGdtYWlsLmNvbSIsImV4cCI6MTc0NDc2NDg1OSwiaXNzIjoiTWVyY3VyaWFsIiwiYXVkIjoiTWVyY3VyaWFsRnJvbnQifQ.tbS1hdHlf7HAl3apdk37DtBm_wXUoKa4npHMoxJ6U1Q

@Refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjBlZjdhMmNkLWUwZmUtNDQ3ZS04YzQ0LWJlYjZlOTM2ZmQ1MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InZhcmdhc2xvYWl6YWNyaXN0aWFuQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2F1dGhlbnRpY2F0aW9uIjoiMWJkOTk5MjYtNDEwMi00OGQyLWJjMDUtMGU2ZWNjNTVjNmE0IiwiZXhwIjoxNzQ1MjgxOTM1LCJpc3MiOiJNZXJjdXJpYWwiLCJhdWQiOiJNZXJjdXJpYWxGcm9udCJ9.84xTtS9RA3NYT0gT-OVsYCGowDHnOJf4WYDFpFQ8Wag

### Create topic
POST {{MercurialBackendDotnet_HostAddress}}/subject
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "title":"Gestión de proyectos"
}

### Updatesubject
PUT {{MercurialBackendDotnet_HostAddress}}/subject
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "subjectId":1,
  "title":"Cloud Computing"
}

### Delete subject
DELETE  {{MercurialBackendDotnet_HostAddress}}/subject/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}


### Get User subjects
GET   {{MercurialBackendDotnet_HostAddress}}/subject?offset=0&limit=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}
