@MercurialBackendDotnet_HostAddress = http://localhost:8000
@Token = 


### Create User
POST  {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Content-Type: application/json

{
  "name": "David",
  "email": "cristiandavidvargas717@gmail.com",
  "password":"Cris-2004"
}


### Update user
PUT {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "name": "Mario Gonorrea"
}

### Delete user
DELETE {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Authorization: Bearer {{Token}}


### Get user overview
GET {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Authorization: Bearer {{Token}}
### Get user overview

POST  {{MercurialBackendDotnet_HostAddress}}/pushnotification
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "token": "David",
  "title": "test",
  "message":"buenas",
  "link":"ksd;aslds",
  "dueDate": "2025-06-07T15:12:00Z"
}

### RecoverAccount
PUT  {{MercurialBackendDotnet_HostAddress}}/user/recoverAccount
Accept: application/json
Content-Type: application/json

{
  "email":"davidclaff4@gmail.com"
}
### RecoverAccount
PUT  {{MercurialBackendDotnet_HostAddress}}/user/changePassword
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "email":"cristiandavidvargas717@gmail.com",
  "code":"CfDJ8KteRa87mGJEkbxBb2VdhqWCUcO x8lTaJxK5kDCAJiouxMg6Tf0iGcWAbn/T3QfEt5akazm5KxozmI WpV2Sis1JUJ3JxkXNny4IjbxGMgTo3P7tqFKoPDsa2IFMTGyBx54fPUz7rq R64Kd918R6Tvp6S 1TQmrcNd0Cqr Gep4xfX0tTpY0rXHrGCzJhtqetro EoQoz8MmhswiJZuMVx1wwfxipsjPjICnmPyq6L",
  "password":"Liliana-2025"
}
