@MercurialBackendDotnet_HostAddress = http://localhost:5066
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjI3ODljNGU1LTE1MTMtNDA2Yy1hNTAwLWQ3OWE4OGMyYzI4YiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImNyaXN0aWFuZGF2aWR2YXJnYXM3MTdAZ21haWwuY29tIiwiZXhwIjoxNzQ0NjU2NDk5LCJpc3MiOiJNZXJjdXJpYWwiLCJhdWQiOiJNZXJjdXJpYWxGcm9udCJ9.JA5uXU64geYIbrvCxFElTih7D3-ookfIY74JSK_VTmY


### Create User
POST  {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Content-Type: application/json

{
  "name": "David",
  "email": "cristiandavidvargas717@gmail.com",
  "password":"Cris-2004"
}


### Update user
PUT {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "name": "Mario Gonorrea"
}

### Delete user
DELETE {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Authorization: Bearer {{Token}}


### Get user overview
GET {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Authorization: Bearer {{Token}}