@MercurialBackendDotnet_HostAddress = http://localhost:5066
@Token = 


### Create User
POST  {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Content-Type: application/json

{
  "name": "David",
  "email": "cristiandavidvargas717@gmail.com",
  "password":"Cris-2004"
}


### Update user
PUT {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "name": "Mario Gonorrea"
}

### Delete user
DELETE {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Authorization: Bearer {{Token}}


### Get user overview
GET {{MercurialBackendDotnet_HostAddress}}/user
Accept: application/json
Authorization: Bearer {{Token}}